# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# 参考链接：https://github.com/marketplace/actions/ssh-deploy#configuration

name: Blog Deploy CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-depoly:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install
      run: yarn install
    
    - name: Build
      run: yarn build
      env:
        CI: true
    
    - name: Deploy to Aliyun
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_ACCESS_TOKEN }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "docs/.vuepress/dist/"
        REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
        REMOTE_USER: ${{ secrets.ALIYUN_USER }}
        TARGET: ${{ secrets.ALIYUN_TARGET }}
